<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <AssemblyName>ssh-agent-echo-gui</AssemblyName>
    <TargetFramework>net10.0</TargetFramework>
    <UseWPF>false</UseWPF>
    <UseWindowsForms>false</UseWindowsForms>
    <Nullable>enable</Nullable>
    <ApplicationManifest>app.manifest</ApplicationManifest>
    <AvaloniaUseCompiledBindingsByDefault>true</AvaloniaUseCompiledBindingsByDefault>
    <ApplicationIcon>..\..\Assets\icon.ico</ApplicationIcon>
    <EnableComSupport>true</EnableComSupport>
  </PropertyGroup>

<PropertyGroup Condition="$([MSBuild]::IsOSPlatform('Linux'))">
  <DefineConstants>LINUX</DefineConstants>
</PropertyGroup>

<PropertyGroup Condition="$([MSBuild]::IsOSPlatform('Windows'))">
  <DefineConstants>WINDOWS</DefineConstants>
  <TargetPlatformVersion>10.0.22621.0</TargetPlatformVersion>
  <TargetPlatformIdentifier>windows</TargetPlatformIdentifier>
</PropertyGroup>

<PropertyGroup Condition="$([MSBuild]::IsOSPlatform('OSX'))">
  <DefineConstants>MACOS</DefineConstants>
</PropertyGroup>

<ItemGroup>
  <PackageReference Include="Avalonia" Version="11.3.11" />
  <PackageReference Include="Avalonia.Desktop" Version="11.3.11" />
  <PackageReference Include="Avalonia.Themes.Fluent" Version="11.3.11" />
  <PackageReference Include="Avalonia.Fonts.Inter" Version="11.3.11" />
  <!--Condition
  below is needed to remove Avalonia.Diagnostics package from build output in Release
  configuration.-->
  <PackageReference Include="Avalonia.Diagnostics" Version="11.3.11">
    <IncludeAssets Condition="'$(Configuration)' != 'Debug'">None</IncludeAssets>
    <PrivateAssets Condition="'$(Configuration)' != 'Debug'">All</PrivateAssets>
  </PackageReference>
  <PackageReference Include="CommunityToolkit.Mvvm" Version="8.4.0" />
  <PackageReference Include="Microsoft.Extensions.Configuration" Version="10.0.3" />
  <PackageReference Include="Microsoft.Extensions.Configuration.Binder" Version="10.0.3" />
  <PackageReference Include="Microsoft.Extensions.Configuration.Json" Version="10.0.3" />
  <PackageReference Include="Semi.Avalonia" Version="11.3.7.3" />
</ItemGroup>

<ItemGroup Condition="$([MSBuild]::IsOSPlatform('Windows'))">
  <PackageReference Include="Microsoft.Toolkit.Uwp.Notifications" Version="7.1.3" />
</ItemGroup>

<ItemGroup Condition="$([MSBuild]::IsOSPlatform('Linux'))">
    <PackageReference Include="Tmds.DBus" Version="0.90.3" />
</ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\SshAgentEcho.Core\SshAgentEcho.Core.csproj" />
  </ItemGroup>
</Project>