name: Build and Release

on:
  push:
    tags:
      - "v*"
  pull_request:
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    strategy:
      matrix:
        include:
          - os: ubuntu-latest
            platform: linux
            artifact: ssh-agent-echo-linux-x64.tar.gz
          - os: windows-latest
            platform: windows
            artifact: ssh-agent-echo-win-x64.zip

    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Get Version from Directory.Build.props
        id: get-version
        shell: bash
        run: echo "version=$(grep -oE '<Version>[^<]+' Directory.Build.props | sed 's/<Version>//')" >> $GITHUB_OUTPUT

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: |
            9.0.x
            10.0.x

      - name: Restore dependencies
        run: dotnet restore

      - name: Build Gui (Linux)
        if: matrix.platform == 'linux'
        run: dotnet publish -c Release -o publish -r linux-x64 --self-contained true -p:PublishSingleFile=true -p:IncludeNativeLibrariesForSelfExtract=true src/SshAgentEcho.Gui/SshAgentEcho.Gui.csproj

      - name: Build Cli (Linux)
        if: matrix.platform == 'linux'
        run: dotnet publish -c Release -o publish -r linux-x64 --self-contained true -p:PublishSingleFile=true -p:IncludeNativeLibrariesForSelfExtract=true src/SshAgentEcho.Cli/SshAgentEcho.Cli.csproj

      - name: Build Gui (Windows)
        if: matrix.platform == 'windows'
        run: dotnet publish -c Release -o publish -r win-x64 --self-contained true -p:PublishSingleFile=true -p:IncludeNativeLibrariesForSelfExtract=true src/SshAgentEcho.Gui/SshAgentEcho.Gui.csproj

      - name: Build Cli (Windows)
        if: matrix.platform == 'windows'
        run: dotnet publish -c Release -o publish -r win-x64 --self-contained true -p:PublishSingleFile=true -p:IncludeNativeLibrariesForSelfExtract=true src/SshAgentEcho.Cli/SshAgentEcho.Cli.csproj

      - name: Compress Linux binaries
        if: matrix.platform == 'linux'
        run: |
          tar -czf ssh-agent-echo-linux-x64.tar.gz -C ./publish ssh-agent-echo-gui ssh-agent-echo

      - name: Install nFPM
        if: matrix.platform == 'linux'
        run: |
          NFPM_VERSION="2.35.3" # Replace with your preferred version
          curl -L https://github.com/goreleaser/nfpm/releases/download/v${NFPM_VERSION}/nfpm_${NFPM_VERSION}_Linux_x86_64.tar.gz | tar xz
          sudo mv nfpm /usr/local/bin/

      - name: Extract Version
        if: matrix.platform == 'linux'
        id: get_version
        run: |
          APP_VERSION=$(grep -oPm1 '(?<=<Version>)[^<]+' Directory.Build.props)
          echo "APP_VERSION=$APP_VERSION" >> $GITHUB_ENV
          echo "Detected version: $APP_VERSION"

      - name: Generate Linux packages
        if: matrix.platform == 'linux'
        run: |
          nfpm pkg --packager deb --target publish/
          nfpm pkg --packager rpm --target publish/
        env:
          APP_VERSION: ${{ env.APP_VERSION }}

      - name: Package Windows Binaries
        if: matrix.platform == 'windows'
        shell: pwsh
        run: |
          $files = @(
            "$PWD/publish/ssh-agent-echo-gui.exe",
            "$PWD/publish/ssh-agent-echo.exe"
            )
            Compress-Archive -Path $files -DestinationPath "$PWD/ssh-agent-echo-win-x64.zip" -Force

      - name: Install NSIS
        if: matrix.platform == 'windows'
        run: |
          iwr -useb get.scoop.sh -outfile 'install.ps1'
          .\install.ps1 -RunAsAdmin
          scoop update
          scoop bucket add extras
          scoop install nsis

      - name: Generate Windows Installer
        if: matrix.platform == 'windows'
        shell: pwsh
        run: |
          & "$env:USERPROFILE\scoop\apps\nsis\current\makensis.exe" .\install.nsi

      - name: Upload artifact
        if: matrix.platform == 'windows'
        uses: actions/upload-artifact@v6
        with:
          name: ${{ matrix.platform }}-binaries
          path: |
            ${{ matrix.artifact }}
            "$PWD/publish/SshAgentEcho-Installer.exe"

      - name: Upload artifact
        if: matrix.platform == 'linux'
        uses: actions/upload-artifact@v6
        with:
          name: ${{ matrix.platform }}-binaries
          path: |
            ${{ matrix.artifact }}
            publish/*.deb
            publish/*.rpm

  release:
    if: startsWith(github.ref, 'refs/tags/')
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Download all artifacts
        uses: actions/download-artifact@v4
        with:
          path: artifacts

      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          draft: false
          prerelease: false
          generate_release_notes: true
          files: |
            artifacts/linux-binaries/ssh-agent-echo-linux-x64.tar.gz
            artifacts/windows-binaries/ssh-agent-echo-win-x64.zip
            artifacts/linux-binaries/publish/*.deb
            artifacts/linux-binaries/publish/*.rpm
            artifacts/windows-binaries/SshAgentEcho-Installer.exe
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
